#!/usr/bin/env bash

USER=squareone
USER_ID=${SQ1_UID:-1000}
GROUP_ID=${SQ1_GID:-1000}

# Returns 1 if the user doesn't exist
USER_EXISTS=$(id -u $USER > /dev/null 2>&1; echo $?)

# user doesn't exist
if [ "$USER_EXISTS" == "1" ]; then
  groupadd -g "$GROUP_ID" "$USER"
  useradd -u "$USER_ID" "$USER" -g "$GROUP_ID"
  usermod -a -G "$USER" www-data
fi

exec "$@"